#pragma once

// Leader key
#define LEADER_TIMEOUT 450
#define LEADER_PER_KEY_TIMING

// Mouse keys
#define MK_COMBINED
#define MOUSEKEY_INTERVAL 8
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 200
#define MOUSEKEY_MAX_SPEED 6
#define MOUSEKEY_WHEEL_DELAY 0

// Tap-hold settings
#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT

// #define UNICODE_SELECTED_MODES UC_MAC
